export const internationalMarketStrategyKnowledge = {
  category: 'International Market Strategy / US-EU AEC Expansion',
  sources: [
    'CP8C Owner brief: Venda EUA Edgard strategic direction',
    'Apex Research / Market Intelligence Studio',
    'Apex Contracts / Permits Studio US-EU package intelligence',
    'Apex BIM / 3D, Revit Customization, Budget, DirectCut and Marketing tools',
  ],
  coreThesis: [
    'The fastest entry path is not positioning the Owner as an architect in the US.',
    'The correct initial positioning is BIM Specialist, Revit Modeler, Permit Set Designer and Residential Construction Documentation partner.',
    'The commercial wedge is offshore technical production for US/EU architecture, engineering, construction and real estate firms.',
    'Render-only, Instagram-only and aesthetics-only positioning are lower priority than technical documentation, BIM, coordination, detailing, permit workflows and production capacity.',
    'The long-term model is an AI BIM Operations Platform / SaaS for AEC offices, supported by a scalable Brazil-based production team.',
  ],
  positioning: {
    primaryTitles: [
      'BIM Specialist',
      'Revit Modeler',
      'Permit Set Designer',
      'Residential Construction Documentation Specialist',
      'Offshore BIM / CAD Production Partner',
    ],
    avoidAsPrimary: [
      'Architect in the US before licensing/market fit is solved',
      'Render-only provider',
      'Instagram-only designer',
      'Aesthetics-only visual service',
      'Generic freelancer without production-system positioning',
    ],
    premiumOffer: [
      'Permit set support',
      'Residential construction documentation',
      'Revit modeling and model cleanup',
      'BIM coordination and clash/preflight support',
      'Estimating and quantity support',
      'Technical documentation automation',
      'AI-powered project delivery workflows',
    ],
  },
  usMarket: {
    highValueRoles: [
      'CAD Drafter',
      'BIM Modeler',
      'Permit Technician',
      'Revit Specialist',
      'Estimator',
      'BIM Coordinator',
      'Residential Designer',
      'Construction Documentation Specialist',
    ],
    highValueServices: [
      'Permit Sets',
      'Residential Construction Docs',
      'Revit Modeling',
      'BIM Coordination',
      'Estimating',
      'Site and floor plan documentation support',
      'MEP coordination support',
    ],
    technicalAwareness: [
      'IRC awareness',
      'IBC awareness',
      'NEC awareness',
      'Florida Building Code awareness',
      'wood framing',
      'drywall systems',
      'roofing systems',
      'HVAC layouts',
      'electrical plans',
      'plumbing plans',
      'foundation types',
    ],
  },
  europeMarket: {
    highValueServices: [
      'BIM documentation',
      'planning permission support',
      'building control documentation',
      'EU/UK permit package support',
      'energy/compliance documentation',
      'technical documentation for architecture and engineering firms',
      'outsourced BIM/CAD production',
    ],
    positioning: [
      'Offshore BIM/CAD production partner for European architecture and engineering offices.',
      'Technical documentation support for planning, building control and compliance packages.',
      'AI-assisted project delivery layer that reduces drafting, coordination and documentation bottlenecks.',
    ],
  },
  businessWorkflow: [
    'Build a 90-day market entry roadmap.',
    'Study US/EU residential documentation, permit package and BIM production standards.',
    'Create an American-style resume and LinkedIn profile around BIM/Revit/Permit Sets/Documentation.',
    'Build a portfolio model focused on permit sets, construction docs, Revit models, details, BIM coordination and estimating examples.',
    'Create an offshore company/production-partner structure instead of thinking only as freelancer/employee.',
    'Build automatic prospecting for US/EU architecture, engineering, builder, remodeler and development firms.',
    'Use premium dollar/euro positioning tied to speed, documentation quality, BIM coordination and AI-powered delivery.',
    'Develop a scalable Brazil-based BIM/CAD production team.',
    'Use Apex AI Copilot as the operating system for research, proposals, permits, BIM, estimating, Revit automation, sales assets and project delivery.',
  ],
  ninetyDayRoadmap: [
    {
      phase: 'Days 1-15',
      focus: 'Positioning and portfolio foundation',
      outputs: ['English positioning statement', 'LinkedIn headline/about', 'portfolio structure', 'sample permit set outline', 'target client list'],
    },
    {
      phase: 'Days 16-45',
      focus: 'Technical proof and outreach system',
      outputs: ['Revit/BIM sample model', 'residential construction document sample', 'permit set sample', 'estimating sample', 'outreach sequences'],
    },
    {
      phase: 'Days 46-75',
      focus: 'Sales execution and agency process',
      outputs: ['proposal templates', 'discovery call script', 'pricing menu', 'production workflow', 'quality checklist'],
    },
    {
      phase: 'Days 76-90',
      focus: 'Scale and platform positioning',
      outputs: ['offshore partner offer', 'AI BIM operations narrative', 'case study', 'SaaS/platform roadmap', 'team hiring/training checklist'],
    },
  ],
  apexBehaviorRules: [
    'When the Owner asks about EUA, Europa, mercado americano, mercado europeu, offshore, BIM em dolar/euro, clientes internacionais, permit sets, portfolio americano, LinkedIn em ingles, prospeccao or operacao remota, use this strategy context.',
    'Prioritize commercial execution, technical positioning and market-entry outputs over generic motivation.',
    'Connect Research Studio, Contracts/Permits, BIM/3D, Revit Customization, Budget, DirectCut and Marketing when useful.',
    'Produce concrete artifacts: LinkedIn positioning, outreach messages, portfolio plan, service menu, 90-day roadmap, proposal copy, target account list criteria and production workflow.',
    'Do not present render-only as the main path unless the user explicitly asks for a visual-only offer.',
    'Always frame legal/licensing/code requirements as awareness or source-verified requirements, not unverified certainty.',
    'If current market data, codes, prices or competitors are needed, route to Research Studio and label unverified items until web/source verification exists.',
  ],
  outputTemplates: [
    'US market positioning statement',
    'EU market positioning statement',
    'LinkedIn headline/about/services in English',
    'Permit set portfolio plan',
    '90-day US/EU market entry roadmap',
    'Offshore BIM/CAD production partner pitch',
    'Cold outreach sequence for architecture/engineering firms',
    'Proposal for permit set / construction documentation support',
    'AI BIM Operations Platform narrative',
  ],
}
