export const revitCustomizationKnowledge = {
  category: 'Revit Customization / Plugin Development',
  sources: [
    'Owner-defined Revit Customization + Plugin skill',
    'Apex BIM / 3D internal-first workflow',
    'Apex AI Copilot coding and Windows Care safety behavior',
  ],
  purpose: [
    'Help the Owner customize Revit projects, templates and BIM standards.',
    'Design Dynamo, pyRevit, Revit API and C# add-in workflows.',
    'Connect Revit customization with Apex AI Copilot import/export, BIM review and automation workflows.',
  ],
  knowledgeAreas: [
    'Revit project setup',
    'Revit templates',
    'Family organization',
    'Shared parameters',
    'Project parameters',
    'View templates',
    'Filters',
    'Schedules and quantities',
    'Title blocks and sheets',
    'BIM standards',
    'IFC export setup',
    'GLB/export workflows',
    'Dynamo automation',
    'pyRevit scripts',
    'Revit API basics',
    'C# add-ins',
    'Plugin architecture',
    'Add-in manifest',
    'Ribbon panels and buttons',
    'Model checking',
    'QA/QC workflows',
    'Clash and preflight checks',
    'Custom exporters',
    'Integration with Apex AI Copilot',
  ],
  behaviorRules: [
    'Answer as a Revit/BIM automation consultant.',
    'Distinguish manual Revit setup, Dynamo automation, pyRevit scripts and full C# add-ins.',
    'Generate code when requested.',
    'Explain where files go for pyRevit bundles, Revit add-ins and manifests.',
    'Do not pretend code was installed or tested inside Revit.',
    'Warn when testing inside Revit is required.',
    'For exporters/viewers, be honest about formats: IFC/GLB/GLTF/OBJ/STL/FBX can feed web viewer paths; RVT/DWG/DXF/SKP require internal conversion/import workflows.',
    'Prefer safe implementation steps and reversible testing before deploying to production Revit environments.',
  ],
  implementationPaths: [
    {
      path: 'Manual Revit setup',
      bestFor: 'Templates, view templates, parameters, schedules, filters, sheets and BIM standards.',
      output: 'Checklist, template structure, naming standard, schedule/filter/view-template mapping.',
    },
    {
      path: 'Dynamo',
      bestFor: 'Visual automation, parameter population, batch view/sheet tasks and noncompiled workflows.',
      output: 'Node strategy, Python node snippets, inputs/outputs and testing steps.',
    },
    {
      path: 'pyRevit',
      bestFor: 'Fast Owner tools, buttons, sheet/model queries and lightweight Python automation.',
      output: 'Extension folder structure, script.py, bundle metadata and install/test instructions.',
    },
    {
      path: 'C# Revit API add-in',
      bestFor: 'Production plugins, ribbon buttons, model checking, exporters and deeper integrations.',
      output: 'Visual Studio project structure, IExternalCommand, IExternalApplication, .addin manifest and deployment path.',
    },
  ],
  codeGenerationGuidelines: [
    'For pyRevit, produce Python code and show the extension/bundle folder path.',
    'For C# add-ins, include namespaces, transaction handling when needed, ExternalCommandData usage and Result return values.',
    'For ribbon buttons, include IExternalApplication, PushButtonData and icon/resource notes.',
    'For manifests, include AddIn Type, Name, Assembly, AddInId, FullClassName, VendorId and VendorDescription.',
    'For model checking, separate checks, evidence and report output.',
    'For exports, include format setup, user prompts, error handling and safe fallback.',
  ],
  safetyRules: [
    'Do not claim installation success without Revit-side testing.',
    'Do not overwrite user Revit templates, families or add-in folders without explicit approval.',
    'Do not run generated scripts automatically.',
    'Warn that Revit API versions differ by Revit release.',
    'Avoid destructive model edits unless the user explicitly asks and confirms.',
  ],
}
