import type { CopilotExecutionCommand } from './copilotExecutionModel'

export const COPILOT_EXECUTION_CWD = 'D:\\AI-constr\\apex-ai-copilot-platform'

export const copilotExecutionCommands: CopilotExecutionCommand[] = [
  {
    id: 'git_status',
    label: 'Git status',
    description: 'Show concise repo status for the authorized Apex Copilot repo.',
    cwd: COPILOT_EXECUTION_CWD,
    executable: 'git',
    args: ['status', '--short'],
    risk: 'low',
    requiresApproval: false,
    timeoutMs: 15000,
    source: 'allowlist',
  },
  {
    id: 'git_log_recent',
    label: 'Recent Git log',
    description: 'Show the five most recent commits.',
    cwd: COPILOT_EXECUTION_CWD,
    executable: 'git',
    args: ['log', '--oneline', '-5'],
    risk: 'low',
    requiresApproval: false,
    timeoutMs: 15000,
    source: 'allowlist',
  },
  {
    id: 'git_diff_stat',
    label: 'Git diff stat',
    description: 'Summarize unstaged and staged file changes without showing full patches.',
    cwd: COPILOT_EXECUTION_CWD,
    executable: 'git',
    args: ['diff', '--stat'],
    risk: 'low',
    requiresApproval: false,
    timeoutMs: 15000,
    source: 'allowlist',
  },
  {
    id: 'git_diff_name_only',
    label: 'Git changed names',
    description: 'List changed file paths only.',
    cwd: COPILOT_EXECUTION_CWD,
    executable: 'git',
    args: ['diff', '--name-only'],
    risk: 'low',
    requiresApproval: false,
    timeoutMs: 15000,
    source: 'allowlist',
  },
  {
    id: 'build',
    label: 'Build',
    description: 'Run the local Vite production build.',
    cwd: COPILOT_EXECUTION_CWD,
    executable: 'npm.cmd',
    args: ['run', 'build'],
    risk: 'medium',
    requiresApproval: false,
    timeoutMs: 120000,
    source: 'allowlist',
  },
  {
    id: 'validate_supabase_sql',
    label: 'Validate Supabase SQL',
    description: 'Run the local read-only Supabase SQL validation script.',
    cwd: COPILOT_EXECUTION_CWD,
    executable: 'npm.cmd',
    args: ['run', 'validate:supabase-sql'],
    risk: 'medium',
    requiresApproval: false,
    timeoutMs: 60000,
    source: 'allowlist',
  },
  {
    id: 'check_server',
    label: 'Check server.mjs',
    description: 'Syntax-check the local Node server.',
    cwd: COPILOT_EXECUTION_CWD,
    executable: 'node',
    args: ['--check', 'server.mjs'],
    risk: 'low',
    requiresApproval: false,
    timeoutMs: 30000,
    source: 'allowlist',
  },
]

export function getCopilotExecutionCommand(commandId: string) {
  return copilotExecutionCommands.find(command => command.id === commandId)
}
