import type { CopilotTool } from './toolRegistry'

export const toolData: CopilotTool[] = [
  {
    id: 'file-intake',
    name: 'Universal File Intake',
    role: 'Accept any file, preview what is safe, and pass context to Copilot.',
    trigger: ['upload', 'file', 'pdf', 'image', 'unknown'],
  },
  {
    id: 'archvis',
    name: 'ArchVis / Humanizacao',
    role: 'Turn plans, images and sketches into render/humanization direction.',
    trigger: ['render', 'plan', 'planta', 'image', 'facade', 'interior'],
  },
  {
    id: 'directcut',
    name: 'DirectCut / Video',
    role: 'Create scripts, shot lists and construction video plans.',
    trigger: ['video', 'timelapse', 'reel', 'tour', 'directcut'],
  },
  {
    id: 'bim-viewer',
    name: 'BIM / 3D Viewer',
    role: 'Open Apex internal BIM / 3D Studio or internal import/conversion workflow.',
    trigger: ['ifc', 'glb', 'gltf', 'obj', 'stl', 'fbx', 'rvt', 'dwg', 'dxf', 'skp', 'bim', 'clash'],
  },
  {
    id: 'budget',
    name: 'Budget / Quantity',
    role: 'Prepare quantity, budget and proposal workflows from project context.',
    trigger: ['budget', 'estimate', 'orcamento', 'quantity', 'takeoff'],
  },
  {
    id: 'contracts',
    name: 'Contracts / Permits',
    role: 'Review contracts, permits, compliance and legal-document workflow context.',
    trigger: ['contract', 'permit', 'legal', 'compliance', 'contrato'],
  },
  {
    id: 'field',
    name: 'Field Operations',
    role: 'Prepare RDO/daily reports, jobsite progress, crew, materials, quality, safety, photo logs and punch lists with evidence labels.',
    trigger: ['field', 'jobsite', 'rdo', 'obra', 'diario de obra', 'relatorio de obra', 'quality', 'safety', 'punch list', 'foto de obra'],
  },
  {
    id: 'marketing',
    name: 'Marketing / Website',
    role: 'Build portfolio, sales page, social and project storytelling outputs.',
    trigger: ['marketing', 'website', 'portfolio', 'social', 'sales'],
  },
  {
    id: 'platform-build',
    name: 'Platform Build Support',
    role: 'Help code, design and rebuild the Apex AI Copilot platform itself.',
    trigger: ['code', 'build', 'platform', 'component', 'api'],
  },
  {
    id: 'coding-support',
    name: 'Code GPT / Coding Assistant',
    role: 'Write, debug, review and explain code across frontend, backend, APIs and automation.',
    trigger: ['code', 'programar', 'programacao', 'debug', 'typescript', 'react', 'api', 'script'],
  },
  {
    id: 'data-analysis',
    name: 'SQL Expert / Data Analyst',
    role: 'Analyze datasets, write SQL, interpret metrics and build decision-ready data narratives.',
    trigger: ['sql', 'data', 'dados', 'analise', 'analytics', 'dashboard', 'metric'],
  },
  {
    id: 'academic-research',
    name: 'Academic Assistant / Research',
    role: 'Support research outlines, summaries, study plans, paper structure and evidence organization.',
    trigger: ['research', 'pesquisa', 'academic', 'paper', 'scholar', 'estudo'],
  },
  {
    id: 'visual-design',
    name: 'DesignerGPT / Visual Designer',
    role: 'Create design direction, logos, visual systems, image prompts and brand concepts.',
    trigger: ['design', 'logo', 'visual', 'brand', 'marca', 'identidade'],
  },
  {
    id: 'negotiation',
    name: 'The Negotiator',
    role: 'Prepare negotiation strategy, scripts, objections, positioning and closing language.',
    trigger: ['negociar', 'negociacao', 'negotiation', 'proposal', 'proposta', 'closing'],
  },
  {
    id: 'tech-support',
    name: 'Tech Support Advisor',
    role: 'Diagnose technical issues, explain fixes and guide operational troubleshooting.',
    trigger: ['erro', 'bug', 'suporte', 'support', 'troubleshoot', 'config'],
  },
  {
    id: 'writing-humanizer',
    name: 'Professional Writing Coach / AI Humanizer',
    role: 'Write, rewrite, humanize, translate and polish professional content.',
    trigger: ['write', 'escreva', 'texto', 'humanizar', 'copy', 'email', 'contrato'],
  },
  {
    id: 'interior-design',
    name: 'Interior / Room Design',
    role: 'Plan rooms, finishes, furniture, lighting, style direction and interior prompts.',
    trigger: ['interior', 'room', 'ambiente', 'decoracao', 'mobiliario', 'furniture'],
  },
  {
    id: 'website-design',
    name: 'Website AI Designer',
    role: 'Create landing pages, portfolios, website copy, sections and conversion flows.',
    trigger: ['landing', 'website', 'site', 'portfolio', 'web', 'pagina'],
  },
  {
    id: 'revit-customization',
    name: 'Revit Customization',
    role: 'Customize Revit templates, parameters, schedules, Dynamo, pyRevit scripts, C# add-ins, ribbon buttons, exporters and Apex integration.',
    trigger: ['revit', 'dynamo', 'pyrevit', 'plugin', 'add-in', 'ribbon', 'shared parameters', 'template bim', 'ifc export', 'c#', 'csharp'],
  },
  {
    id: 'research-market-intelligence',
    name: 'Research / Market Intelligence',
    role: 'Prepare source-aware market research, competitor analysis, pricing/SINAPI checks and proposal intelligence without fake current data.',
    trigger: ['pesquisa', 'market research', 'concorrentes', 'competitor', 'sinapi', 'preco atualizado', 'pricing research', 'benchmark'],
  },
  {
    id: 'international-market-strategy',
    name: 'International Market Strategy',
    role: 'Build US/EU market-entry strategy for offshore BIM/CAD/Revit, permit sets, construction documentation, estimating, LinkedIn/outreach and AI-powered AEC delivery.',
    trigger: ['eua', 'usa', 'europa', 'offshore', 'international clients', 'permit sets', 'linkedin', 'bim em dolar', 'revit', 'construction documentation'],
  },
  {
    id: 'platform-engineering-devops',
    name: 'Platform Engineering / DevOps',
    role: 'Review repos, organize code, plan branches/PRs, generate Supabase SQL/RLS, diagnose Vercel/build issues and audit security without fake access or fake deploy claims.',
    trigger: ['github', 'repo', 'branch', 'pr', 'supabase', 'sql', 'vercel', 'deploy', 'backend', 'frontend', 'database', 'security', 'vulnerability', 'refactor', 'code review'],
  },
  {
    id: 'export-center',
    name: 'Export Center',
    role: 'Package real project workspace outputs from all studios into redacted JSON, Markdown, TXT, CSV or ZIP-compatible bundles.',
    trigger: ['exportar', 'export package', 'baixar pacote', 'client package', 'exportar projeto', 'exportar rdo', 'exportar orçamento'],
  },
  {
    id: 'saas-crm-finance',
    name: 'SaaS / CRM / Finance',
    role: 'Model local-first users, roles, client workspaces, CRM, proposals, finance, accounting preparation and SaaS plans without fake auth, payments or database claims.',
    trigger: ['crm', 'lead', 'cliente', 'vendas', 'financeiro', 'fatura', 'pagamento', 'plano saas', 'usuário', 'permissões', 'contabilidade', 'contador', 'contas a receber'],
  },
  {
    id: 'cognitive-agents',
    name: 'Cognitive Agents',
    role: 'Expose the 8 Apex cognitive agents, their connected studios, evidence rules, implementation status, gaps and next checkpoints.',
    trigger: ['agentes', '8 agentes', 'cognitive agents', 'maestro', 'bim manager', 'evm', 'nr compliance', 'cost controller', 'doc manager', 'scheduler', 'quality qa'],
  },
  {
    id: 'evm-scheduler-compliance',
    name: 'EVM / Scheduler / NR Compliance',
    role: 'Run local EVM, Gantt-style scheduling, physical-financial planning and NR safety compliance analysis without fake real-time data or official certification.',
    trigger: ['evm', 'cpi', 'spi', 'eac', 'vac', 'tcpi', 'planned value', 'earned value', 'actual cost', 'cronograma', 'gantt', 'caminho crítico', 'atraso', 'lookahead', 'cronograma físico-financeiro', 'nr-18', 'nr-35', 'nr-10', 'nr-6', 'nr-33', 'segurança do trabalho', 'compliance nr'],
  },
  {
    id: 'supply-chain',
    name: 'Supply Chain / Suppliers',
    role: 'Manage local supplier registry, procurement items, RFQs and supplier comparisons without fake ERP, price, availability or verification.',
    trigger: ['fornecedor', 'fornecedores', 'supply chain', 'cotação', 'cotacao', 'rfq', 'compra', 'material', 'materiais', 'subcontratado', 'procurement', 'supplier'],
  },
  {
    id: 'notifications-alerts',
    name: 'Notifications / Alerts',
    role: 'Create local alerts for deadlines, cost deviation, safety, quality, permits, payments, suppliers and AI thresholds without fake push/email/SMS.',
    trigger: ['alerta', 'notificação', 'notificacao', 'prazo', 'lembrete', 'pendência', 'pendencia', 'vencimento', 'atraso crítico', 'deadline', 'notification'],
  },
  {
    id: 'ai-cost-observability',
    name: 'AI Cost / Observability',
    role: 'Track estimated local AI usage and cost by module/project/model without fake provider billing.',
    trigger: ['custo de ia', 'gasto com ia', 'tokens', 'observabilidade', 'custo openai', 'ai cost', 'billing', 'usage dashboard'],
  },
  {
    id: 'exploration',
    name: 'Exploration / General Reasoning',
    role: 'Think through open-ended questions, strategy, planning, decisions and general knowledge tasks.',
    trigger: ['explore', 'pensar', 'ideia', 'estrategia', 'strategy', 'geral'],
  },
]
