/**
 * server/service/americanPermits.mjs
 *
 * American Permits — documentacao para aprovacao de projetos nos EUA.
 * Baseado em floor plan upload, gera checklists, formularios e relatorios.
 */

const PROJECTS = new Map()

const PERMIT_TYPES = [
  { id: 'building-permit', name: 'Building Permit', description: 'Permissão para construção/ reforma' },
  { id: 'planning-permission', name: 'Planning Permission', description: 'Aprovação de planejamento urbano' },
  { id: 'zoning', name: 'Zoning Compliance', description: 'Conformidade com zoneamento' },
  { id: 'fire-marshal', name: 'Fire Marshal Review', description: 'Aprovação do corpo de bombeiros' },
  { id: 'ada', name: 'ADA Compliance', description: 'Acessibilidade (Americans with Disabilities Act)' },
  { id: 'structural', name: 'Structural Review', description: 'Revisão estrutural por engenheiro' },
  { id: 'mep', name: 'MEP Permit', description: 'Permissão de sistemas MEP' },
  { id: 'occupancy', name: 'Certificate of Occupancy', description: 'Certificado de ocupação' },
]

export function createPermitProject(data) {
  const id = `permit-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
  const project = {
    id, status: 'draft',
    projectName: String(data.projectName || '').trim(),
    address: String(data.address || '').trim(),
    city: String(data.city || '').trim(),
    state: String(data.state || '').trim(),
    zipCode: String(data.zipCode || '').trim(),
    buildingType: data.buildingType || 'residential',
    squareFootage: Number(data.squareFootage) || 0,
    floors: Number(data.floors) || 1,
    permitTypes: Array.isArray(data.permitTypes) ? data.permitTypes : ['building-permit'],
    hasFloorPlan: Boolean(data.hasFloorPlan),
    engineerName: String(data.engineerName || 'Dr. Edgard').trim(),
    engineerLicense: String(data.engineerLicense || '').trim(),
    documents: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
  PROJECTS.set(id, project)
  return project
}

export function getPermitProject(id) { return PROJECTS.get(id) || null }
export function listPermitProjects() {
  return Array.from(PROJECTS.values()).sort((a, b) => b.createdAt.localeCompare(a.createdAt))
}

export function generatePermitChecklist(projectId) {
  const p = PROJECTS.get(projectId)
  if (!p) return null

  const checklist = p.permitTypes.map(pid => {
    const info = PERMIT_TYPES.find(pt => pt.id === pid) || { id: pid, name: pid, description: '' }
    return {
      permitType: info.id,
      permitName: info.name,
      description: info.description,
      requiredDocs: [
        'Floor plan (planta baixa)',
        'Site plan (implantação)',
        'Elevations (fachadas)',
        'Sections (cortes)',
        p.buildingType === 'commercial' ? 'Fire protection plan' : null,
        p.floors > 2 ? 'Structural calculations' : null,
        p.squareFootage > 5000 ? 'MEP drawings' : null,
        'Energy compliance certificate',
        'Owner authorization letter',
      ].filter(Boolean),
      estimatedFee: p.buildingType === 'commercial' ? 500 + p.squareFootage * 0.5 : 200 + p.squareFootage * 0.3,
      estimatedTimeline: p.permitTypes.length > 3 ? '8-16 weeks' : '4-8 weeks',
      status: 'pending',
    }
  })

  return {
    projectName: p.projectName,
    address: p.address,
    city: p.city,
    state: p.state,
    engineer: p.engineerName,
    license: p.engineerLicense,
    checklist,
    summary: `Total de ${checklist.length} permit(s) necessários. Estimativa de custo: $${checklist.reduce((s, c) => s + c.estimatedFee, 0).toFixed(2)}`,
    generatedAt: new Date().toISOString(),
  }
}

export function generatePermitReport(projectId) {
  const p = PROJECTS.get(projectId)
  if (!p) return null

  return {
    projectName: p.projectName,
    address: `${p.address}, ${p.city}, ${p.state} ${p.zipCode}`,
    buildingType: p.buildingType,
    squareFootage: p.squareFootage,
    floors: p.floors,
    responsibleEngineer: p.engineerName,
    licenseNumber: p.engineerLicense,
    permitRequirements: p.permitTypes.map(pid => {
      const info = PERMIT_TYPES.find(pt => pt.id === pid)
      return `- ${info?.name || pid}: ${info?.description || ''}`
    }).join('\n'),
    submittedBy: p.engineerName,
    signature: `[ASSINATURA DIGITAL - ${p.engineerName}]`,
    date: new Date().toISOString(),
    formHtml: `<form><h2>Permit Application - ${p.projectName}</h2><p><strong>Project:</strong> ${p.projectName}</p><p><strong>Address:</strong> ${p.address}, ${p.city}, ${p.state}</p><p><strong>Engineer:</strong> ${p.engineerName} | License: ${p.engineerLicense}</p><p><strong>Permits Required:</strong></p><ul>${p.permitTypes.map(pid => { const i = PERMIT_TYPES.find(pt => pt.id === pid); return `<li>${i?.name || pid}</li>`; }).join('')}</ul><hr/><p><em>Generated by Apex AI - ${new Date().toLocaleDateString('en-US')}</em></p></form>`,
  }
}
