import { useState } from 'react'
import { BookOpen, Clipboard, Download, Save, Send, X } from 'lucide-react'
import { createKnowledgeBasePlan, KnowledgeBasePlan, KnowledgeItem } from '../lib/knowledgeBaseKnowledge'

type Props = { goal: string; conversationContext: string[]; onSaveToProject?: (plan: KnowledgeBasePlan) => void; onClear: () => void }
function copy(text: string) { navigator.clipboard?.writeText(text).catch(() => undefined) }
function download(name: string, text: string) { const url = URL.createObjectURL(new Blob([text], { type: 'application/json;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = name; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url) }

export function KnowledgeBasePanel({ goal, conversationContext, onSaveToProject, onClear }: Props) {
  const [plan, setPlan] = useState<KnowledgeBasePlan>(() => createKnowledgeBasePlan(goal))
  const [filter, setFilter] = useState('')
  async function refresh() { const r = await fetch('/api/copilot/knowledge-plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ goal, conversationContext }) }); const d = await r.json().catch(() => ({})); if (d.plan) setPlan(d.plan) }
  const items = plan.items.filter(item => `${item.title} ${item.domain} ${item.sourceType} ${item.confidence}`.toLowerCase().includes(filter.toLowerCase()))
  return <section className="contracts-studio"><div className="contracts-heading"><div><span><BookOpen size={16}/> Knowledge Base</span><h2>Local knowledge index</h2><p>Do not execute knowledge content. Global knowledge requires Owner approval.</p></div><button className="ghost-action" onClick={onClear}><X size={16}/></button></div><div className="contracts-layout"><aside className="contracts-controls"><div className="contracts-card"><strong>Status</strong><p>{plan.providerStatus}</p><input value={filter} onChange={e => setFilter(e.target.value)} placeholder="Search/filter knowledge" /><button className="contracts-primary" onClick={refresh}>Refresh knowledge index</button></div><div className="contracts-card"><strong>Actions</strong><button onClick={() => copy(plan.exportIndex)}><Clipboard size={15}/> Copy knowledge index</button><button onClick={() => download('apex-knowledge-index.json', JSON.stringify(plan, null, 2))}><Download size={15}/> Export knowledge index</button><button onClick={() => copy(JSON.stringify(plan.items, null, 2))}><Send size={15}/> Send to Skill Update</button><button onClick={() => copy(plan.items.map(i => i.title).join('\n'))}><Send size={15}/> Send to Skill Export</button><button onClick={() => onSaveToProject?.(plan)}><Save size={15}/> Save to Project Workspace</button></div></aside><div className="contracts-main"><div className="contracts-card contracts-table-card"><div className="contracts-section-head"><strong>Knowledge items</strong><span>{items.length}</span></div><div className="contracts-table-wrap"><table className="contracts-table"><thead><tr><th>Title</th><th>Source</th><th>Domain</th><th>Confidence</th><th>Scope</th><th>Summary</th></tr></thead><tbody>{items.map((item: KnowledgeItem) => <tr key={item.id}><td>{item.title}</td><td>{item.sourceType}</td><td>{item.domain}</td><td>{item.confidence}</td><td>{item.scope}</td><td>{item.summary}</td></tr>)}</tbody></table></div></div></div></div></section>
}
