export const archvisKnowledge = {
  category: 'ArchVis / Humanizacao',
  sources: [
    'humanizacao.md',
    'humanize-floor-plan/SKILL.md',
    'humanize-floor-plan/references/ai-prompts-and-resources.md',
    'prompt gemini para realismo em plan mais importante para render.txt',
    'prompt para fachada do revit.txt',
    'PROMPT PLANTA HUMANIZADA ING.pdf',
    'PROMPT POS PLANTA HUMANIZADA PT.pdf',
    '30--Prompts--Profissionais--para--Arquitetura--e--Design--de--Interiores.pdf',
    'Prompts Arquitetonicos AI.pdf',
    'apex-global-orchestrator/references/render-3d-humanization.md',
    'apex-global-orchestrator/references/render-prompts-library.md',
  ],
  principles: [
    'Chat remains primary; ArchVis is an output/tool panel called by Apex AI Copilot.',
    'For faithful work, use image-to-image and preserve the source geometry.',
    'Humanized floor plan output must be top-down, orthographic and aligned to the original plan.',
    'Only enhance visible existing zones; do not invent rooms, gardens, decks, patios or service yards.',
    'Creative redesign must be labeled as creative concept, not faithful plan.',
  ],
  workflows: [
    'Upload floor plan or architectural image.',
    'Copilot analyzes visible geometry, rooms, exterior areas, pool, access, lot shape and user goal.',
    'Choose preserve plan or creative concept.',
    'Build prompt from subject, style, materials/details, lighting and camera.',
    'Run image connector only when the source image and mode are compatible.',
    'Return honest provider status; never fake generated images.',
  ],
  preserveExactPlanRules: [
    'Use strict image-to-image.',
    'Preserve exact lot boundary, exact building footprint and exact exterior/service areas.',
    'Preserve layout, walls, openings, room positions, labels where possible, pool, garage, road/access and proportions.',
    'Do not change geometry, add rooms, remove rooms, move pool, move road, crop the plan or create a 3D facade.',
    'Do not fill blank/white/technical zones with invented landscaping.',
    'If an area is unclear, keep it neutral.',
  ],
  creativeRules: [
    'Creative redesign may imagine a new concept and stronger visual identity.',
    'Creative output must say it is not construction-accurate or faithful to the plan.',
    'Use facade, interior, cinematic and marketing language when the user asks for exploration.',
  ],
}
