export const imagePromptKnowledge = {
  category: 'Image prompts / visual design',
  anatomy: ['subject', 'style', 'details/materials', 'lighting', 'camera'],
  stylePresets: [
    'humanized floor plan',
    'photorealistic facade',
    'minimalist residence',
    'urban building',
    'rural guesthouse',
    'brutalist/futuristic',
    'sustainable house',
    'coastal/beach house',
    'interior design',
    'futuristic interior',
    'technical BIM/MEP',
    'topographic hologram',
    'masterplan overlay',
  ],
  negativePrompts: [
    'changed geometry',
    'altered walls',
    'missing rooms',
    'extra rooms',
    'moved pool',
    'moved road',
    'invented garden',
    'added patio',
    'perspective distortion',
    'cartoon style',
    'unrealistic furniture scale',
    'misspelled labels',
    'filename text in image',
    'cropped plan',
  ],
}
